name: Node.js CI

on:
  push:
    branches:
      - "deployment"
      - "production"
  pull_request:
    branches:
      - "deployment"
      - "production"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json', '.github/workflows/*') }}
        restore-keys: |
          npm-${{ runner.os }}-
    - run: |
        cd application
        npm install  # Ensure dependencies are installed before proceeding
    - name: Build the application
      run: |
        cd application
        npm run build  # Run the build command inside the 'application' directory
    - run: npm test
